# Generated by Django 5.2.4 on 2025-07-06 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pull_time', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DataChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('added', 'Added'), ('removed', 'Removed'), ('modified', 'Modified')], max_length=10)),
                ('provider', models.TextField()),
                ('previous_data', models.JSONField(blank=True, null=True)),
                ('current_data', models.JSONField(blank=True, null=True)),
                ('change_time', models.DateTimeField(auto_now_add=True)),
                ('data_pull', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_scrap.datapull')),
            ],
        ),
        migrations.CreateModel(
            name='CIAData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.TextField()),
                ('city', models.CharField(max_length=512)),
                ('state', models.CharField(max_length=512)),
                ('effective', models.CharField(max_length=20)),
                ('press_release', models.URLField(blank=True, null=True)),
                ('record_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CIA_data_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CIA_data_updated_by', to=settings.AUTH_USER_MODEL)),
                ('data_pull', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_scrap.datapull')),
            ],
        ),
    ]
